export type HttpMethod = 'get' | 'post' | 'put' | 'delete' | 'patch' | 'head' | 'options' | 'trace'

export enum HttpRequestHeader {
  /**
   * standard header fields
   */
  ACCEPT = "accept",
  ACCEPT_CHARSET = "accept-charset",
  ACCEPT_DATETIME = "accept-datetime",
  ACCEPT_ENCODING = "accept-encoding",
  ACCEPT_LANGUAGE = "accept-language",
  ACCESS_CONTROL_REQUEST_METHOD = "access-control-request-method",
  ACCESS_CONTROL_REQUEST_HEADERS = "access-control-request-headers",
  AUTHORIZATION = "authorization",
  A_IM = "a-im",
  CACHE_CONTROL = "cache-control",
  CONNECTION = "connection",
  CONTENT_LENGTH = "content-length",
  CONTENT_MD5 = "content-md5",
  CONTENT_TYPE = "content-type",
  COOKIE = "cookie",
  DATE = "date",
  EXPECT = "expect",
  FORWARDED = "forwarded",
  FROM = "from",
  HOST = "host",
  HTTP2_SETTINGS = "http2-settings",
  IF_MATCH = "if-match",
  IF_MODIFIED_SINCE = "if-modified-since",
  IF_NONE_MATCH = "if-none-match",
  IF_RANGE = "if-range",
  IF_UNMODIFIED_SINCE = "if-unmodified-since",
  MAX_FORWARDS = "max-forwards",
  ORIGIN = "origin",
  PRAGMA = "pragma",
  PROXY_AUTHORIZATION = "proxy-authorization",
  RANGE = "range",
  REFERER = "referer",
  TE = "te",
  TRAILER = "trailer",
  TRANSFER_ENCODING = "transfer-encoding",
  UPGRADE = "upgrade",
  USER_AGENT = "user-agent",
  VIA = "via",
  WARNING = "warning",
  /**
   * non standard common header fields
   */
  DNT = "dnt",
  FRONT_END_HTTPS = "front-end-https",
  PROXY_CONNECTION = "proxy-connection",
  SAVE_DATA = "save-data",
  UPGRADE_INSECURE_REQUESTS = "upgrade-insecure-requests",
  X_ATT_DEVICEID = "x-att-deviceid",
  X_CORRELATION_ID = "x-correlation-id",
  X_CSRF_TOKEN = "x-csrf-token",
  X_FORWARDED_FOR = "x-forwarded-for",
  X_FORWARDED_HOST = "x-forwarded-host",
  X_FORWARDED_PROTO = "x-forwarded-proto",
  X_HTTP_METHOD_OVERRIDE = "x-http-method-override",
  X_REQUEST_ID = "x-request-id",
  X_REQUESTED_WITH = "x-requested-with",
  X_UIDH = "x-uidh",
  X_WAP_PROFILE = "x-wap-profile",
}

export enum HttpResponseHeader {
  /**
   * standard header fields
   */
  ACCEPT_PATCH = "accept-patch",
  ACCEPT_RANGES = "accept-ranges",
  ACCESS_CONTROL_ALLOW_CREDENTIALS = "access-control-allow-credentials",
  ACCESS_CONTROL_ALLOW_HEADERS = "access-control-allow-headers",
  ACCESS_CONTROL_ALLOW_METHODS = "access-control-allow-methods",
  ACCESS_CONTROL_ALLOW_ORIGIN = "access-control-allow-origin",
  ACCESS_CONTROL_EXPOSE_HEADERS = "access-control-expose-headers",
  ACCESS_CONTROL_MAX_AGE = "access-control-max-age",
  AGE = "age",
  ALLOW = "allow",
  ALT_SVC = "alt-svc",
  CACHE_CONTROL = "cache-control",
  CONNECTION = "connection",
  CONTENT_DISPOSITION = "content-disposition",
  CONTENT_ENCODING = "content-encoding",
  CONTENT_LANGUAGE = "content-language",
  CONTENT_LENGTH = "content-length",
  CONTENT_LOCATION = "content-location",
  CONTENT_MD5 = "content-md5",
  CONTENT_RANGE = "content-range",
  CONTENT_TYPE = "content-type",
  DATE = "date",
  DELTA_BASE = "delta-base",
  ETAG = "etag",
  EXPIRES = "expires",
  IM = "im",
  LAST_MODIFIED = "last-modified",
  LINK = "link",
  LOCATION = "location",
  P3P = "p3p",
  PRAGMA = "pragma",
  PROXY_AUTHENTICATE = "proxy-authenticate",
  PUBLIC_KEY_PINS = "public-key-pins",
  RETRY_AFTER = "retry-after",
  SERVER = "server",
  SET_COOKIE = "set-cookie",
  STRICT_TRANSPORT_SECURITY = "strict-transport-security",
  TK = "tk",
  TRAILER = "trailer",
  TRANSFER_ENCODING = "transfer-encoding",
  UPGRADE = "upgrade",
  VARY = "vary",
  VIA = "via",
  WARNING = "warning",
  WWW_AUTHENTICATE = "www-authenticate",
  X_FRAME_OPTIONS = "x-frame-options",
  /**
   * non standard common header fields
   */
  CONTENT_SECURITY_POLICY = "content-security-policy",
  X_CONTENT_SECURITY_POLICY = "x-content-security-policy",
  X_WEBKIT_CSP = "x-webkit-csp",
  REFRESH = "refresh",
  STATUS = "status",
  TIMING_ALLOW_ORIGIN = "timing-allow-origin",
  X_CONTENT_DURATION = "x-content-duration",
  X_CONTENT_TYPE_OPTIONS = "x-content-type-options",
  X_POWERED_BY = "x-powered-by",
  X_REQUEST_ID = "x-request-id",
  X_CORRELATION_ID = "x-correlation-id",
  X_UA_COMPATIBLE = "x-ua-compatible",
  X_XSS_PROTECTION = "x-xss-protection",
}

export enum HttpStatus {
  CONTINUE = 100,
  SWITCHING = 101,
  PROCESSING = 102,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  ALREADY_REPORTED = 208,
  IM_USED = 226,
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  REQUEST_ENTITY_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  POLICY_NOT_FULFILLED = 420,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO = 431,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  VARIANT_ALSO_NEGOTIATES = 506,
  INSUFFICIENT_STORAGE = 507,
  LOOP_DETECTED = 508,
  BANDWIDTH_LIMIT_EXCEEDED = 509,
  NOT_EXTENDED = 510,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
}
