export const mimeTypes = {
  AAC: "audio/aac",
  BIN: "application/octet-stream",
  CSS: "text/css",
  CSV: "text/csv",
  DOC: "application/msword",
  DOCX: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  GIF: "image/gif",
  GZ: "application/gzip",
  HTML: "text/html",
  ICS: "text/calendar",
  JPG: "image/jpeg",
  JS: "text/javascript",
  JSON: "application/json",
  MP3: "audio/mpeg",
  MP4: "video/mp4",
  OGA: "audio/ogg",
  OGV: "video/ogg",
  PDF: "application/pdf",
  PNG: "image/png",
  SVG: "image/svg+xml",
  TXT: "text/plain",
  WEBP: "image/webp",
  XLS: "application/vnd.ms-excel",
  XLSX: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  XML: "application/xml",
  ZIP: "application/zip",
} as const

export type MimeType = (typeof mimeTypes)[keyof typeof mimeTypes]