name: Node Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24, 26]
    steps:
      - uses: actions/checkout@v7
      - name: Setup pnpm on node@${{ matrix.node-version }}
        uses: pnpm/setup@v2
        with:
          runtime: node@{{ matrix.node-version }}
      - name: Format check
        run: pnpm fmt:check
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test

